### PR TITLE
Fixed incorrect inheritance for ModuleHint_F

### LINKED ISSUE #449: UBC - ModuleBootcampStage_F -> Module_F
**Arma 3 Version:** `1.88` (stable)  
**CBA Version:** `3.9.1` (stable)  
**Achilles Version:** `3.12.5` (stable)  

**Mods:**
```
- CBA_A3
- Achilles
```

**Description:**
```
13:49:18 Updating base class ModuleBootcampStage_F->Module_F, by achilles\modules_f_achilles\config.bin/CfgVehicles/ModuleHint_F/ (original a3\modules_f_bootcamp\misc\config.bin)
```

**Steps to reproduce:**
- Run the game.

**Where did the issue occur?**
- Environment: All
- Mission: None

**RPT log file:**
- Pasted under description.

### PR DESCRIPTION
**Pull request by CreepPork**
**When merged this pull request will:**
- Fix #449

### CODE REVIEW

File: @AresModAchillesExpansion/addons/modules_f_achilles/Zeus/cfgVehiclesModulesZeus.hpp [hunk 1]
```diff
@@ -20,9 +20,11 @@ class Achilles_Module_Zeus_AssignZeus : Achilles_Zeus_Module_Base
 	icon = "\achilles\data_f_achilles\icons\icon_unit.paa";
 	portrait = "\achilles\data_f_achilles\icons\icon_unit.paa";
 };
-class ModuleHint_F : Module_F
+
+class ModuleBootcampStage_F;
+class ModuleHint_F : ModuleBootcampStage_F
 {
-	scopeCurator = 1;
+	scopeCurator = 2;
```
Comment (oOKexOo) [inline @AresModAchillesExpansion/addons/modules_f_achilles/Zeus/cfgVehiclesModulesZeus.hpp]: Why?

Comment (oOKexOo) [inline @AresModAchillesExpansion/addons/modules_f_achilles/Zeus/cfgVehiclesModulesZeus.hpp]: Why?

Comment (CreepPork) [reply @AresModAchillesExpansion/addons/modules_f_achilles/Zeus/cfgVehiclesModulesZeus.hpp]: Because otherwise, the module is hidden and cannot be accesed. Like right now on release, you can’t find it.
